// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_-McCfYohtNfR3uJ24OFtI-6ALDtJ2c',
    appId: '1:965153041589:web:e91153a52a5d33ee29a2fc',
    messagingSenderId: '965153041589',
    projectId: 'home-plant-app-dav',
    authDomain: 'home-plant-app-dav.firebaseapp.com',
    storageBucket: 'home-plant-app-dav.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-w-QtGmhGDaFhlL6aKuTei5O3YMxhwZM',
    appId: '1:965153041589:android:7ea5486bf4532c0529a2fc',
    messagingSenderId: '965153041589',
    projectId: 'home-plant-app-dav',
    storageBucket: 'home-plant-app-dav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt9UiouSiekCoZtKzEO94jVBKxWH9e0ms',
    appId: '1:965153041589:ios:237eaa5efe68c63a29a2fc',
    messagingSenderId: '965153041589',
    projectId: 'home-plant-app-dav',
    storageBucket: 'home-plant-app-dav.firebasestorage.app',
    iosBundleId: 'com.ducanhlaai.plantCareApp',
  );
}
